### ISSUE TITLE
Unable to download database

### ISSUE THREAD

**Issue by edxu96** [zequnyu/cmdict#72]
All the commands lead to:

```
Traceback (most recent call last):
  File "/usr/local/bin/cmdict", line 5, in <module>
    from cmdict import run_script
  File "/usr/local/lib/python3.8/site-packages/cmdict/__init__.py", line 2, in <module>
    from cmdict import run_script
  File "/usr/local/lib/python3.8/site-packages/cmdict/run_script.py", line 13, in <module>
    from cmdict.ecdict_connector import ecdict_engine
  File "/usr/local/lib/python3.8/site-packages/cmdict/ecdict_connector.py", line 106, in <module>
    ecdict_engine = ECDICTConnector()
  File "/usr/local/lib/python3.8/site-packages/cmdict/ecdict_connector.py", line 48, in __init__
    raise ValueError("Database file is missing or invalid.")
ValueError: Database file is missing or invalid.
```

It seems that `ECDICTConnector()` is always called before any attempt to download can be made.

**Comment by edxu96** [comment]
Note that when you uninstall `cmdict` using `pip`, files in `site-packages/cmdict/db` will be kept.

**Comment by zequnyu** [comment]
> Note that when you uninstall `cmdict` using `pip`, files in `site-packages/cmdict/db` will be kept.

We can probably provide a `clean` command to remove it. For now I think it's ok.

**Comment by zequnyu** [comment]
#76.
